### ISSUE TITLE
Button and leave-alerts are inconsistent

### ISSUE THREAD

**Issue by mmitteregger-bearingpoint** [infonova/infocmdb#53]
Displayed buttons are inconsistent in their visibility and order.

Additionally the "Are you sure?"-type leave alerts are sometimes shown and other times not.
In my opinion they should always been shown if there were some edits or simply always be sown if the edited condition is hard to check. This prevents losing important work.

The following describes the current display:

Menu:
* Create CI inside browsed CI Type
  * Buttons: [Save] [Cancel]
  * Cancel button alert: yes
* Create CI from outer menu
  * Buttons: [Save] [Cancel]
  * Cancel button alert: yes
* Create CI Type
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* Create Attribute
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* Create Relation Type
  * Buttons: [Cancel] [Save]
  * Cancel button alert: no
* Create Attribute Group
  * Buttons: [Save]
  * Cancel button alert: not possible
* Create Announcement
  * Buttons: [Save] [Cancel]
  * Cancel button alert: no
* Create User
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* Create Role
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* Create Theme
  * Buttons: [Cancel] [Save]
  * Cancel button alert: no
* Create Project
  * Buttons: [Cancel] [Save]
  * Cancel button alert: no
* Create Workflow
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* Create Report
  * Buttons: [Back] [Cancel] [Save] [Next]
  * Cancel button alert: no
* File Import
  * Buttons: [Abort] [Back] [Next] [Start]
  * Cancel button alert: no
* Create Mailimport
  * Buttons: [Save]
  * Cancel button alert: not possible
* Create Notification Template
  * Buttons: [Save]
  * Cancel button alert: not possible
* Create Webservice
  * Buttons: [Save] [Cancel]
  * Cancel button alert: no
* Edit Menu
  * Buttons: [Save] **LINEBREAK** [Cancel]
  * Cancel button alert: no

Some buttons are shown conditionally (f.e. [Next] only if there is a next tab), the list above states a button if it can be shown at the page at all. For example the "Create CI inside browsed CI Type" form could have tabs, but no [Back] or [Next] buttons are shown there ever.

What are other websites doing?
* Github (New issue)
[Submit new issue] button without any cancel button.
Button is floating on the right.

* Jira (Create Issue)
[Create] on the left side. [Cancel] on the right.
The [Cancel] button displays a alert.
Buttons are displayed very differently with a strong focus on [Create].
The buttongroup is floating on the right.

**Comment by rwese** [comment]
fixes
