### ISSUE TITLE
Go workflow names cannot end with "_test"

### ISSUE THREAD

**Issue by mmitteregger-bearingpoint** [infonova/infocmdb#88]
When creating a go workflow that ends with "_test" the code can't be compiled.

The workflows are currently stored as `<workflow_name>/<workflow_name>.go` along with a test file `<workflow_name>/<workflow_name>_test.go`.
But because the files end `_test` go treats it as a test file:
`go build <build_directory>: no non-test Go files in <build_directory>`.

Suggestion:
The workflow name is already present in the directory name and the workflow file already contains a `package main` declaration, so the files should be named `main.go` and `main_test.go`.

**Comment by mmitteregger-bearingpoint** [comment]
### Implementation plan

The workflow names are also stored in the workflow_task table.
This contains 3 important columns for this issue:
* name
* script
* scriptname

Additionally to the migration on the filesystem all of these three columns also need to be migrated to always contain "main.go".
Note that only golang workflows must be migrated. Perl workflows depend on each other by name and thus cannot be easily changed without careful consideration given to of all existing workflows.

**Comment by rwese** [comment]
A simpler workaround was to disallow `..._test` as a name.
